# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pactivisme/Documents/Projects/Perso/CPP/weedlyweb/weedlyweb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pactivisme/Documents/Projects/Perso/CPP/weedlyweb/weedlyweb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pactivisme/Documents/Projects/Perso/CPP/weedlyweb/weedlyweb/CMakeFiles /home/pactivisme/Documents/Projects/Perso/CPP/weedlyweb/weedlyweb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pactivisme/Documents/Projects/Perso/CPP/weedlyweb/weedlyweb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WeedlyWeb

# Build rule for target.
WeedlyWeb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WeedlyWeb
.PHONY : WeedlyWeb

# fast build rule for target.
WeedlyWeb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/build
.PHONY : WeedlyWeb/fast

#=============================================================================
# Target rules for targets named custom_clean

# Build rule for target.
custom_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 custom_clean
.PHONY : custom_clean

# fast build rule for target.
custom_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/custom_clean.dir/build.make CMakeFiles/custom_clean.dir/build
.PHONY : custom_clean/fast

src/GestionnaireFichiers.o: src/GestionnaireFichiers.cpp.o
.PHONY : src/GestionnaireFichiers.o

# target to build an object file
src/GestionnaireFichiers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireFichiers.cpp.o
.PHONY : src/GestionnaireFichiers.cpp.o

src/GestionnaireFichiers.i: src/GestionnaireFichiers.cpp.i
.PHONY : src/GestionnaireFichiers.i

# target to preprocess a source file
src/GestionnaireFichiers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireFichiers.cpp.i
.PHONY : src/GestionnaireFichiers.cpp.i

src/GestionnaireFichiers.s: src/GestionnaireFichiers.cpp.s
.PHONY : src/GestionnaireFichiers.s

# target to generate assembly for a file
src/GestionnaireFichiers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireFichiers.cpp.s
.PHONY : src/GestionnaireFichiers.cpp.s

src/GestionnaireHTTP.o: src/GestionnaireHTTP.cpp.o
.PHONY : src/GestionnaireHTTP.o

# target to build an object file
src/GestionnaireHTTP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireHTTP.cpp.o
.PHONY : src/GestionnaireHTTP.cpp.o

src/GestionnaireHTTP.i: src/GestionnaireHTTP.cpp.i
.PHONY : src/GestionnaireHTTP.i

# target to preprocess a source file
src/GestionnaireHTTP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireHTTP.cpp.i
.PHONY : src/GestionnaireHTTP.cpp.i

src/GestionnaireHTTP.s: src/GestionnaireHTTP.cpp.s
.PHONY : src/GestionnaireHTTP.s

# target to generate assembly for a file
src/GestionnaireHTTP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireHTTP.cpp.s
.PHONY : src/GestionnaireHTTP.cpp.s

src/GestionnaireMemoire.o: src/GestionnaireMemoire.cpp.o
.PHONY : src/GestionnaireMemoire.o

# target to build an object file
src/GestionnaireMemoire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireMemoire.cpp.o
.PHONY : src/GestionnaireMemoire.cpp.o

src/GestionnaireMemoire.i: src/GestionnaireMemoire.cpp.i
.PHONY : src/GestionnaireMemoire.i

# target to preprocess a source file
src/GestionnaireMemoire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireMemoire.cpp.i
.PHONY : src/GestionnaireMemoire.cpp.i

src/GestionnaireMemoire.s: src/GestionnaireMemoire.cpp.s
.PHONY : src/GestionnaireMemoire.s

# target to generate assembly for a file
src/GestionnaireMemoire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/GestionnaireMemoire.cpp.s
.PHONY : src/GestionnaireMemoire.cpp.s

src/MoteurRendu.o: src/MoteurRendu.cpp.o
.PHONY : src/MoteurRendu.o

# target to build an object file
src/MoteurRendu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/MoteurRendu.cpp.o
.PHONY : src/MoteurRendu.cpp.o

src/MoteurRendu.i: src/MoteurRendu.cpp.i
.PHONY : src/MoteurRendu.i

# target to preprocess a source file
src/MoteurRendu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/MoteurRendu.cpp.i
.PHONY : src/MoteurRendu.cpp.i

src/MoteurRendu.s: src/MoteurRendu.cpp.s
.PHONY : src/MoteurRendu.s

# target to generate assembly for a file
src/MoteurRendu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/MoteurRendu.cpp.s
.PHONY : src/MoteurRendu.cpp.s

src/Navigateur.o: src/Navigateur.cpp.o
.PHONY : src/Navigateur.o

# target to build an object file
src/Navigateur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/Navigateur.cpp.o
.PHONY : src/Navigateur.cpp.o

src/Navigateur.i: src/Navigateur.cpp.i
.PHONY : src/Navigateur.i

# target to preprocess a source file
src/Navigateur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/Navigateur.cpp.i
.PHONY : src/Navigateur.cpp.i

src/Navigateur.s: src/Navigateur.cpp.s
.PHONY : src/Navigateur.s

# target to generate assembly for a file
src/Navigateur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/Navigateur.cpp.s
.PHONY : src/Navigateur.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WeedlyWeb.dir/build.make CMakeFiles/WeedlyWeb.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... custom_clean"
	@echo "... WeedlyWeb"
	@echo "... src/GestionnaireFichiers.o"
	@echo "... src/GestionnaireFichiers.i"
	@echo "... src/GestionnaireFichiers.s"
	@echo "... src/GestionnaireHTTP.o"
	@echo "... src/GestionnaireHTTP.i"
	@echo "... src/GestionnaireHTTP.s"
	@echo "... src/GestionnaireMemoire.o"
	@echo "... src/GestionnaireMemoire.i"
	@echo "... src/GestionnaireMemoire.s"
	@echo "... src/MoteurRendu.o"
	@echo "... src/MoteurRendu.i"
	@echo "... src/MoteurRendu.s"
	@echo "... src/Navigateur.o"
	@echo "... src/Navigateur.i"
	@echo "... src/Navigateur.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

